language: rust
env:
- zipname="px8-$TRAVIS_OS_NAME.tar.gz"

sudo: required

cache: cargo

os:
- linux
- osx

dist: trusty

rust:
- stable
- beta
- nightly

matrix:
  allow_failures:
  - rust: nightly

before_install:
- export PATH="$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
  sed "s|::|:|g")"

install:
- sudo add-apt-repository ppa:team-xbmc/ppa -y
- sudo apt-get update -q
- sudo apt-get install libsdl2-dev
- export PYTHON_LIB=$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
- export LIBRARY_PATH="$LIBRARY_PATH:$PYTHON_LIB"
- export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$PYTHON_LIB"

addons:
  apt:
    packages:
    - python3

script:
- cargo build --verbose
- cargo test --verbose
- cargo build --features="cpython lua dyon" --verbose
- cargo test --features="cpython lua dyon" --verbose
- cargo build --features="sdl_renderer" --verbose
- cargo test --features="sdl_renderer" --verbose
- cargo build --features="sdl_renderer cpython lua dyon" --verbose
- cargo test --features="sdl_renderer cpython lua dyon" --verbose

before_deploy:
- mv target/release/px8 .
- tar -zcvf $zipname px8 sys

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: R42tjaO08EoICVp3+9qD5UgJz3fRydo+B3UJkfp/VGxWilON8tkMmHLxUri+Whgz41WSy7s88BgR2wG/WnY98Lw35fKtQ3WxnVySwoiQixYBUw+LsjMU+9wsqOPICTWTMBG1L6Ad+G0y2EC87qY1pcZxM6/QoHJfoZF+NTI2topZgQMg/0bTlxW674ZR8OiTIwWKkR4LIp0rq8aUiX28LEzkfdYnUCvs3U9mMIeMVLNQsgnoIT8vDTHvYcTN5Yn//O/+k3glOjuCJ4X8gUWrbRfqPajLwT7E6ywXcM9PGb/8RjEIQQlZSafOcxdmPD8HSRKoM6geCVGK2V45IoHRuh1svSmB3UhGDyfBaF6JafC/ViKLBQpFkDqH66fFDMGxYzRfvnW4aWcHeSU5pBJ+39q1eKKaMAWeV4QCLPCfMeq9Fzk6tVdGN9ObRW4oIGkoQTOwHQ+qEI4lw1StyVV5jGedZM6O6Sog61miHu1MZ39bHeGoSVlAZ+u7w5MSN+wBIJwvgCVTeysS7Eu5OeUbmlsHceQceBAOFfoXZWRNykB4ikdoSr5AMva0K+jqx6sVbtMwS3xXoxbzxi0sngjf65ZHoR/qN5FTImCe4l9FqhaxerDXHMuQZ5qxrUErq3+v4Gc9KNJ3GRaBBrQTZwMBV+ijVRJmiYW/ZmFmRyatDF4=
  file: $zipname
  on:
    repo: Gigoteur/PX8
    tags: true