language: rust

sudo: required

rust:
    - stable
    - beta 
    - nightly

matrix:
  allow_failures:
    - rust: nightly

install:
  - export PYTHON_LIB=$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
  - export LIBRARY_PATH="$LIBRARY_PATH:$PYTHON_LIB"
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$PYTHON_LIB

addons:
  apt:
    packages:
      - python3
