dist: trusty
language: rust
services: docker
sudo: required

rust: stable

env:
  global:
    - TARGET=x86_64-unknown-linux-gnu

# matrix:
#  include:
#   - env: TARGET=armv7-unknown-linux-gnueabihf DEPLOY=1
#    - env: TARGET=x86_64-unknown-linux-gnu DEPLOY=1

before_install:
- set -e
- export PATH="$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
  sed "s|::|:|g")"

install:
- sudo apt-get update -q
- sudo apt-get install libsdl2-dev
- export PYTHON_LIB=$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
- export LIBRARY_PATH="$LIBRARY_PATH:$PYTHON_LIB"
- export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$PYTHON_LIB"

addons:
  apt:
    packages:
      - python3

script:
  - bash unicorn-travis/script.sh

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo