language: rust

sudo: required

dist: trusty

rust:
    - stable
    - beta 
    - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - export PATH="$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")"

install:
  # Install SDL2
  - sudo add-apt-repository ppa:team-xbmc/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install libsdl2-dev
  - export PYTHON_LIB=$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
  - export LIBRARY_PATH="$LIBRARY_PATH:$PYTHON_LIB"
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$PYTHON_LIB"

addons:
  apt:
    packages:
      - python3

script:
  - cargo build --features="cpython lua" --verbose
  - cargo test --features="cpython lua" --verbose
