environment:
    global:
        PROJECT_NAME: PX8
    matrix:
        - TARGET: x86_64-pc-windows-msvc
          CHANNEL: stable
          PY: 3
          PYTHONPATH: C:\Python34-x64
          FEATURES: python3-sys

matrix:
    allow_failures:
        - CHANNEL: nightly

install:
    - set PATH=C:\msys64\usr\bin;%PATH%
    - set PATH=C:\msys64\mingw32\bin;%PATH%
    - if "%TARGET%" == "x86_64-pc-windows-gnu" set PATH=C:\msys64\mingw64\bin;%PATH%
    - curl -sSf -o rustup-init.exe https://win.rustup.rs
    - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - rustc -Vv
    - SET PATH=%PYTHONPATH%;%PATH%
    - python --version

build: false

test_script:
    - cargo build --features="cpython" --verbose --release

cache:
    - target
    - C:\Users\appveyor\.cargo\registry