image:
  - Visual Studio 2017

environment:
    global:
        PROJECT_NAME: PX8
    matrix:
        - TARGET: x86_64-pc-windows-msvc
          CHANNEL: stable
          PY: 3
          PYTHONPATH: C:\Python34-x64
          FEATURES: python3-sys

matrix:
    allow_failures:
        - CHANNEL: nightly

install:
    # Print Powershell version.
    - ps: $PSVersionTable.PSVersion
    - ps: pwd

    # Install MSYS2 and MINGW (32-bit & 64-bit)
    - ps: |
        # Check if MSYS2 was restored from cache
        if($env:MINGW_DIR) {
          if($env:MINGW_DIR -eq "mingw32") {
            # Download and install MINGW (32-bit)
            Write-Host "Installing MinGW (32-bit)..." -ForegroundColor Cyan
            Write-Host "Downloading installation package..."
            appveyor DownloadFile https://s3.amazonaws.com/rust-lang-ci/i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z -FileName mingw.7z
          } elseif($env:MINGW_DIR -eq "mingw64") {
            # Download and install MINGW (64-bit)
            Write-Host "Installing MinGW (64-bit)..." -ForegroundColor Cyan
            Write-Host "Downloading installation package..."
            appveyor DownloadFile https://s3.amazonaws.com/rust-lang-ci/x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z -FileName mingw.7z
          }
          Write-Host "Extracting installation package..."
          7z x -y mingw.7z -oC:\msys64 | Out-Null
          del mingw.7z
        } else {
          Write-Host "MSYS2 not required" -ForegroundColor Green
        }

    - if defined MINGW_DIR set PATH=C:\msys64\%MINGW_DIR%\bin;C:\msys64\usr\bin;%PATH%

    - set FEATURES=
    - if defined BUILD_MSI set FEATURES=--features msi-installed

    - curl -sSf -o rustup-init.exe https://win.rustup.rs
    - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - rustc -Vv
    - SET PATH=%PYTHONPATH%;%PATH%
    - python --version

    # Install SDL2.
    - curl --fail --silent --show-error --location --output sdl2.zip https://www.libsdl.org/release/SDL2-devel-2.0.5-VC.zip
    - ps: Expand-Archive sdl2.zip -DestinationPath sdl2
    - set LIB=%LIB%;C:\projects\PX8\sdl2\SDL2-2.0.5\lib\x64

    # Install SDL2_Mixer.
    - curl --fail --silent --show-error --location --output sdl2_mixer.zip https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.1-VC.zip
    - ps: Expand-Archive sdl2_mixer.zip -DestinationPath sdl2_mixer
    - set LIB=%LIB%;C:\projects\PX8\sdl2_mixer\SDL2_mixer-2.0.1\lib\x64
    - ps: Get-ChildItem -Recurse -Depth 4

build: false

test_script:
    - cargo build --features="cpython lua" --verbose --release

cache:
    - target
    - C:\Users\appveyor\.cargo\registry