[package]
name = "px8"
version = "0.0.1"
authors = ["hallucino <d@t0t0.fr>"]
description = "Open source fantasy console in Rust"
documentation = "Fantasy Console with support of Python/Lua for the cartridge"
homepage = "https://github.com/Gigoteur/PX8"
repository = "https://github.com/Gigoteur/PX8"
readme = "README.md"
keywords = ["rust", "console", "python", "lua", "fantasy", "8bits"]
license = "MIT"

exclude = [ ".idea/*", ".travis.yml" ]

[dependencies]
time = "*"
regex = "*"
png = "*"
byteorder = "*"
rand = "*"
libc = "*"
chan ="*"
log = "*"
env_logger = "*"
rusttype = "*"
getopts = "*"
sdl2 = "*"
nalgebra = "*"
image = "*"
gif = "*"
cpython = "*"
rustc-serialize = "*"
chrono = "*"

[dependencies.lua]
git = "https://github.com/jcmoyer/rust-lua53"

[dependencies.glium]
version = "*"
default-features = false